os: osx
language: objective-c
matrix:
  include:
    - osx_image: xcode8.2
      env: SWFT=3.0
    - osx_image: xcode8.3
      env: SWFT=3.1
    - osx_image: xcode9
      env: SWIFT=3.2
    - osx_image: xcode9
      env: SWFT=4.0
before_install:
  - export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /iPhone SE .* \[(.*)\]/; if \$1; puts(\$1); exit; end }");
install:
  - carthage bootstrap --platform iOS
script:
  - set -o pipefail;
    open -a "simulator" --args -CurrentDeviceUDID "$UUID";
    xcodebuild -scheme PMKAVFoundation SWIFT_VERSION=$SWFT -destination "id=$UUID" -quiet clean build;
    xcodebuild -scheme PMKAVFoundation -destination "id=$UUID" -quiet test
