use_frameworks!

target 'Wolf_Example' do
  pod 'Wolf/Unbox', :path => '../'
  pod 'Nuke', '~> 4.1'
  pod 'OHHTTPStubs', '~> 5.2'
  pod 'OHHTTPStubs/Swift', '~> 5.2'
  pod 'IBentifiers', '~> 0.1'

  target 'Wolf_Tests' do
    pod 'Wolf/Unbox', :path => '../'
    pod 'Nimble', '~> 5.0'
    pod 'OHHTTPStubs', '~> 5.2'
    pod 'OHHTTPStubs/Swift', '~> 5.2'
  end
end
