use_frameworks!

target 'Wolf_Example' do
  pod 'Wolf', :path => '../'

  target 'Wolf_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
    pod 'OHHTTPStubs', '~> 5.1'
    pod 'OHHTTPStubs/Swift', '~> 5.1'
  end
end
