os: osx
language: objective-c
matrix:
  include:
    - osx_image: xcode8.2
      env: PLAT=iOS SWFT=3.0
    - osx_image: xcode8.2
      env: PLAT=watchOS SWFT=3.0
    - osx_image: xcode8.3
      env: PLAT=iOS SWFT=3.1
    - osx_image: xcode8.3
      env: PLAT=watchOS SWFT=3.1
    - osx_image: xcode9
      env: PLAT=iOS SWFT=3.2
    - osx_image: xcode9
      env: PLAT=watchOS SWFT=3.2
    - osx_image: xcode9
      env: PLAT=iOS SWFT=4.0
    - osx_image: xcode9
      env: PLAT=watchOS SWFT=4.0
before_install:
  - case $PLAT in
    iOS)
      NAME="iPhone SE";;
    watchOS)
      NAME="Apple Watch - 38mm";;
    esac
  - if [ -n "$NAME" ]; then
      export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /$NAME .* \[(.*)\]/; if \$1; puts(\$1); exit; end }");
      export DESTINATION="id=$UUID";
    fi
install:
  - carthage bootstrap --platform $PLAT
script:
  - set -o pipefail;
    case $PLAT in
    iOS)
      open -b com.apple.iphonesimulator --args -CurrentDeviceUDID "$UUID";
      xcodebuild -scheme PMKWatchConnectivity -quiet -destination "$DESTINATION" build clean SWIFT_VERSION=$SWFT;
      xcodebuild -scheme PMKWatchConnectivity -quiet -destination "$DESTINATION" test;;
    watchOS)
      xcodebuild -scheme PMKWatchConnectivity -quiet -destination "$DESTINATION" -quiet clean build SWIFT_VERSION=$SWFT;;
    esac
