language: objective-c
osx_image: xcode8.3
env:
  - DESTINATION="arch=x86_64"                    PLATFORM=Mac
  - DESTINATION="OS=10.3.1,name=iPhone SE"       PLATFORM=iOS
  - DESTINATION="OS=9.3,name=iPhone SE"          PLATFORM=iOS
  - DESTINATION="OS=8.4,name=iPhone 4s"          PLATFORM=iOS
  - DESTINATION="OS=10.2,name=Apple TV 1080p"    PLATFORM=tvOS
  - DESTINATION="OS=9.0,name=Apple TV 1080p"     PLATFORM=tvOS
install:
  - carthage bootstrap --platform $PLATFORM
script:
  - set -o pipefail
  - xcodebuild -scheme PMKSystemConfiguration -destination "$DESTINATION" clean build
  - xcodebuild -scheme PMKSystemConfiguration -destination "$DESTINATION" test
