os: osx
language: objective-c
matrix:
  include:
    - osx_image: xcode8.2
      env: PLAT=macOS SWFT=3.0
    - osx_image: xcode8.2
      env: PLAT=iOS SWFT=3.0
    - osx_image: xcode8.3
      env: PLAT=macOS SWFT=3.1
    - osx_image: xcode8.3
      env: PLAT=iOS SWFT=3.1
    - osx_image: xcode9
      env: PLAT=macOS SWFT=3.2
    - osx_image: xcode9
      env: PLAT=iOS SWFT=3.2
    - osx_image: xcode9
      env: PLAT=macOS SWFT=4.0
    - osx_image: xcode9
      env: PLAT=iOS SWFT=4.0
before_install:
  - if [ $PLAT == "iOS" ]; then
      export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /iPhone SE .* \[(.*)\]/; if \$1; puts(\$1); exit; end }");
    fi
install:
  - case $PLAT in
    macOS)
      carthage bootstrap --platform Mac;;
    *)
      carthage bootstrap --platform $PLAT;;
    esac;
script:
  - set -o pipefail;
    case $PLAT in
    macOS)
      xcodebuild -scheme PMKAccounts -quiet clean build SWIFT_VERSION=$SWFT;
      xcodebuild -scheme PMKAccounts -quiet test;;
    iOS)
      open -b com.apple.iphonesimulator --args -CurrentDeviceUDID "$UUID";
      xcodebuild -scheme PMKAccounts -destination "id=$UUID" -quiet clean build SWIFT_VERSION=$SWFT;
      xcodebuild -scheme PMKAccounts -destination "id=$UUID" -quiet test;;
    esac
